# Generated by Django 5.0.1 on 2024-01-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('edad', models.PositiveSmallIntegerField()),
                ('correo', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=20)),
                ('area_desempenio', models.CharField(choices=[('RH', 'RRHH'), ('FN', 'FINANZAS'), ('VN', 'VENTAS'), ('BD', 'BODEGA'), ('PRD', 'PRODUCCION')], max_length=300)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('dias_Vacaciones', models.IntegerField()),
                ('dias_Administrativos', models.IntegerField()),
                ('fecha_contrato', models.DateField()),
                ('fecha_termino_contrato', models.DateField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
