# Generated by Django 5.0.1 on 2024-01-23 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_usuario_contrasena_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='estado',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
